### ISSUE TITLE
Merge with awesome-academic-writing

### ISSUE THREAD

**Issue by ashwinvis** [writing-resources/awesome-scientific-writing#15]
We now need to merge the contents of https://github.com/maehr/awesome-academic-writing here

What headings should we can structure so that we get best of both worlds?

- *Converters / Word Processors /* ... ?
- *Extras / ...?*   should be split up or discarded
- *How To / Demos / Tips and Tricks / Templates and Guides /* ..?
- *Spell checking / Linters ?*

Unique headings which should be kept!
- *Bibliography*
- *Illustrations*

**Comment by ashwinvis** [comment]
ping @maehr

**Comment by maehr** [comment]
Hey @ashwinvis 

Sorry, I didn't mean to keep you waiting.

Disclaimer: My philosophy so far has been to put only free and open source software on my list that I really use every day - so I focused on Pandoc Markdown. It was also important for me that academics with little technical knowledge could also use the tools proposed by my list. Furthermore: Please excuse my blunt words; I am not a native speaker. I want to achieve the best possible result and am always open to compromise.

Some remarks on your list:

- What markup language do you use in your daily work? Do you really write with all formats (Org-Mode, RST and Markdown)? I would like to limit the list to one specific format to make it more intuitive and applicable for everyday use.
- The Converter section can be resolved, are boiled down to Pandoc and Org. https://github.com/BubuAnabelas/awesome-markdown/#readme already lists all relevant converters.
- There is some overlap with https://github.com/markusschanta/awesome-jupyter/#renderingpublishingconversion and https://github.com/egeerardyn/awesome-LaTeX/ which we could reduce by focusing on one specific markup language.
- Although I like the visual aids, I would do without the emoticons. ⭐️ and Σ are redundant because they apply to all items, 🔗 and 🔖  depend heavily on your specific setup.
- Linting and spell checking are not the same thing. We can split this into two sections.

---

I would suggest the following structure

---

*An introductory text about who we want to help with the list.*

## Contents

- Word processors
- Bibliography
- Illustrations
- Spell Checking
- Templates
  - Articles
  - Presentations
  - Books
- Linters
- Tutorials
  - Working with XX (i.e. Markdown, Org..)
  - Academic writing in general

**Comment by ashwinvis** [comment]
Great input! I agree with most of your comments and the layout. Some remarks though:

> What markup language do you use in your daily work?

I use everything listed except org-mode. Each have their special purpose (blog/docs: rst, exploratory work: ipynb, articles: markdown). We can skip org-mode since it is emacs specific. 

But what I use may not be someone else's jam. So if I see sufficient support in the form of demos or tutorials which use different markup / tools, I include them.

> About overlap with other lists focussing on a format & visual aids

That is OK I think. I had a hard time deciding the format of my thesis text, because I was concerned about matching with LaTeX capabilities. A single list focussing on scientific writing would understand the limitations of the tools. +1 on removing the redundant visual aids.

**Comment by maehr** [comment]
I will make a pull request in the coming days and implement my changes. If you want to revise your list according to my remarks, let me know - otherwise we'll do the same work twice.
I would be happy if you would add me to the organization. As logo I suggest the following https://openmoji.org/library/#search=writing&emoji=270D

As soon as we are finished we can merge our pending PRs on https://github.com/sindresorhus/awesome.

Thanks for the uncomplicated cooperation.

**Comment by ashwinvis** [comment]
I already invited you to the organizations. I will try to fix your remarks until tonight, and then you can make a branch for content.

The logo is OK, but give me a few days to see if I can find something more apt

**Comment by maehr** [comment]
The invite expired. Can you invite me again?

**Comment by ashwinvis** [comment]
Did it work?

**Comment by ashwinvis** [comment]
All yours now!
